import { logger } from '@/lib/logger';
import {
  getGeminiApiErrorMessage,
  isGeminiLocationUnsupported,
} from './gemini-error-utils';

/**
 * Generate a short title (10-30 characters) from user message using AI
 * Falls back to truncating the message if AI generation fails
 */
export async function generateProjectTitle(
  userMessage: string
): Promise<string> {
  // Fallback: use first 30 characters if message is short
  const fallbackTitle = userMessage.slice(0, 30).trim();

  // If message is already short enough, use it directly
  if (userMessage.length <= 30) {
    return fallbackTitle;
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      logger.ai.warn(
        '[Title Generator] GEMINI_API_KEY not set, using fallback'
      );
      return fallbackTitle;
    }

    // Use Gemini API to generate title
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000); // 5秒超时

    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey,
        },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `请用中文将以下图片生成描述总结为一个10-30字的简短中文标题。无论输入是什么语言，标题必须是中文。只返回标题文本，不要引号或其他内容。\n\n描述：${userMessage}`,
                },
              ],
            },
          ],
          generationConfig: {
            maxOutputTokens: 50,
            temperature: 0.7,
          },
        }),
      }
    );

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text();
      const reason = getGeminiApiErrorMessage(response.status, errorText);
      logger.ai.warn(
        `[Title Generator] Gemini API failed: ${response.status}`,
        {
          error: errorText,
          reason,
        }
      );
      if (isGeminiLocationUnsupported(errorText)) {
        logger.ai.warn(
          '[Title Generator] Falling back because Gemini is unavailable in the current server region'
        );
      }
      return fallbackTitle;
    }

    const data = await response.json();
    const generatedTitle =
      data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!generatedTitle) {
      logger.ai.warn('[Title Generator] No title generated by Gemini');
      return fallbackTitle;
    }

    // Remove quotes if present
    const cleanTitle = generatedTitle.replace(/^["']|["']$/g, '').trim();

    // Limit to 60 characters max (database constraint)
    const finalTitle = cleanTitle.slice(0, 60);

    logger.ai.info(
      `[Title Generator] Generated title: "${finalTitle}" from message: "${userMessage.slice(0, 50)}..."`
    );

    return finalTitle;
  } catch (error) {
    if (error instanceof Error && error.name === 'AbortError') {
      logger.ai.warn('[Title Generator] Request timeout, using fallback');
    } else {
      logger.ai.error('[Title Generator] Error generating title:', error);
    }
    return fallbackTitle;
  }
}
